/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FarmerID = IDL.Int;
export const Session = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
});
export const MilkType = IDL.Variant({
  'vlc' : IDL.Null,
  'thekadari' : IDL.Null,
});
export const Time = IDL.Int;
export const CollectionEntry = IDL.Record({
  'id' : IDL.Int,
  'fat' : IDL.Float64,
  'snf' : IDL.Opt(IDL.Float64),
  'weight' : IDL.Float64,
  'farmerID' : FarmerID,
  'date' : Time,
  'rate' : IDL.Float64,
  'milkType' : MilkType,
  'session' : Session,
});
export const Farmer = IDL.Record({
  'name' : IDL.Text,
  'milkType' : MilkType,
  'customerID' : FarmerID,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({ 'name' : IDL.Text });
export const InventoryEntry = IDL.Record({
  'quantityInStock' : IDL.Float64,
  'product' : Product,
});
export const ProductSale = IDL.Record({
  'id' : IDL.Int,
  'farmerID' : IDL.Opt(FarmerID),
  'productName' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Int,
  'farmerID' : FarmerID,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCollectionEntry' : IDL.Func(
      [
        FarmerID,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Float64,
        Session,
      ],
      [],
      [],
    ),
  'addFarmer' : IDL.Func([IDL.Text, IDL.Text, MilkType], [FarmerID], []),
  'addInventoryEntry' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addProductSale' : IDL.Func(
      [IDL.Opt(FarmerID), IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Int],
      [],
    ),
  'addTransaction' : IDL.Func([FarmerID, IDL.Text, IDL.Float64], [IDL.Int], []),
  'getAllCollectionsForSession' : IDL.Func(
      [Session, IDL.Nat],
      [IDL.Vec(CollectionEntry)],
      ['query'],
    ),
  'getAllFarmers' : IDL.Func([], [IDL.Vec(Farmer)], ['query']),
  'getAllInventory' : IDL.Func([], [IDL.Vec(InventoryEntry)], ['query']),
  'getAllProductSales' : IDL.Func([], [IDL.Vec(ProductSale)], ['query']),
  'getFarmer' : IDL.Func([FarmerID], [Farmer], ['query']),
  'getFarmerBalance' : IDL.Func([FarmerID], [IDL.Float64], ['query']),
  'getFarmerTransactions' : IDL.Func(
      [FarmerID, IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getPaginatedCollections' : IDL.Func(
      [FarmerID, IDL.Nat],
      [IDL.Vec(CollectionEntry)],
      ['query'],
    ),
  'getRates' : IDL.Func(
      [],
      [IDL.Record({ 'vlc' : IDL.Float64, 'thekadari' : IDL.Float64 })],
      ['query'],
    ),
  'updateCollectionEntry' : IDL.Func(
      [
        FarmerID,
        IDL.Int,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Float64,
        Session,
        MilkType,
      ],
      [],
      [],
    ),
  'updateFarmerDetails' : IDL.Func(
      [FarmerID, IDL.Text, IDL.Text, MilkType, FarmerID],
      [],
      [],
    ),
  'updateInventory' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateProductSale' : IDL.Func(
      [IDL.Int, IDL.Opt(FarmerID), IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateRates' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'updateTransaction' : IDL.Func(
      [FarmerID, IDL.Int, IDL.Text, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FarmerID = IDL.Int;
  const Session = IDL.Variant({ 'morning' : IDL.Null, 'evening' : IDL.Null });
  const MilkType = IDL.Variant({ 'vlc' : IDL.Null, 'thekadari' : IDL.Null });
  const Time = IDL.Int;
  const CollectionEntry = IDL.Record({
    'id' : IDL.Int,
    'fat' : IDL.Float64,
    'snf' : IDL.Opt(IDL.Float64),
    'weight' : IDL.Float64,
    'farmerID' : FarmerID,
    'date' : Time,
    'rate' : IDL.Float64,
    'milkType' : MilkType,
    'session' : Session,
  });
  const Farmer = IDL.Record({
    'name' : IDL.Text,
    'milkType' : MilkType,
    'customerID' : FarmerID,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({ 'name' : IDL.Text });
  const InventoryEntry = IDL.Record({
    'quantityInStock' : IDL.Float64,
    'product' : Product,
  });
  const ProductSale = IDL.Record({
    'id' : IDL.Int,
    'farmerID' : IDL.Opt(FarmerID),
    'productName' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Int,
    'farmerID' : FarmerID,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCollectionEntry' : IDL.Func(
        [
          FarmerID,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Float64,
          Session,
        ],
        [],
        [],
      ),
    'addFarmer' : IDL.Func([IDL.Text, IDL.Text, MilkType], [FarmerID], []),
    'addInventoryEntry' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addProductSale' : IDL.Func(
        [IDL.Opt(FarmerID), IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Int],
        [],
      ),
    'addTransaction' : IDL.Func(
        [FarmerID, IDL.Text, IDL.Float64],
        [IDL.Int],
        [],
      ),
    'getAllCollectionsForSession' : IDL.Func(
        [Session, IDL.Nat],
        [IDL.Vec(CollectionEntry)],
        ['query'],
      ),
    'getAllFarmers' : IDL.Func([], [IDL.Vec(Farmer)], ['query']),
    'getAllInventory' : IDL.Func([], [IDL.Vec(InventoryEntry)], ['query']),
    'getAllProductSales' : IDL.Func([], [IDL.Vec(ProductSale)], ['query']),
    'getFarmer' : IDL.Func([FarmerID], [Farmer], ['query']),
    'getFarmerBalance' : IDL.Func([FarmerID], [IDL.Float64], ['query']),
    'getFarmerTransactions' : IDL.Func(
        [FarmerID, IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getPaginatedCollections' : IDL.Func(
        [FarmerID, IDL.Nat],
        [IDL.Vec(CollectionEntry)],
        ['query'],
      ),
    'getRates' : IDL.Func(
        [],
        [IDL.Record({ 'vlc' : IDL.Float64, 'thekadari' : IDL.Float64 })],
        ['query'],
      ),
    'updateCollectionEntry' : IDL.Func(
        [
          FarmerID,
          IDL.Int,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Float64,
          Session,
          MilkType,
        ],
        [],
        [],
      ),
    'updateFarmerDetails' : IDL.Func(
        [FarmerID, IDL.Text, IDL.Text, MilkType, FarmerID],
        [],
        [],
      ),
    'updateInventory' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateProductSale' : IDL.Func(
        [IDL.Int, IDL.Opt(FarmerID), IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateRates' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'updateTransaction' : IDL.Func(
        [FarmerID, IDL.Int, IDL.Text, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };