/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CollectionEntry {
  'id' : bigint,
  'fat' : number,
  'snf' : [] | [number],
  'weight' : number,
  'farmerID' : FarmerID,
  'date' : Time,
  'rate' : number,
  'milkType' : MilkType,
  'session' : Session,
}
export interface Farmer {
  'name' : string,
  'milkType' : MilkType,
  'customerID' : FarmerID,
  'phone' : string,
}
export type FarmerID = bigint;
export interface InventoryEntry {
  'quantityInStock' : number,
  'product' : Product,
}
export type MilkType = { 'vlc' : null } |
  { 'thekadari' : null };
export interface Product { 'name' : string }
export interface ProductSale {
  'id' : bigint,
  'farmerID' : [] | [FarmerID],
  'productName' : string,
  'pricePerUnit' : number,
  'totalAmount' : number,
  'timestamp' : Time,
  'quantity' : number,
}
export type Session = { 'morning' : null } |
  { 'evening' : null };
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'farmerID' : FarmerID,
  'description' : string,
  'timestamp' : Time,
  'amount' : number,
}
export interface _SERVICE {
  'addCollectionEntry' : ActorMethod<
    [FarmerID, number, number, [] | [number], number, Session],
    undefined
  >,
  'addFarmer' : ActorMethod<[string, string, MilkType], FarmerID>,
  'addInventoryEntry' : ActorMethod<[string, number], undefined>,
  'addProductSale' : ActorMethod<
    [[] | [FarmerID], string, number, number],
    bigint
  >,
  'addTransaction' : ActorMethod<[FarmerID, string, number], bigint>,
  'getAllCollectionsForSession' : ActorMethod<
    [Session, bigint],
    Array<CollectionEntry>
  >,
  'getAllFarmers' : ActorMethod<[], Array<Farmer>>,
  'getAllInventory' : ActorMethod<[], Array<InventoryEntry>>,
  'getAllProductSales' : ActorMethod<[], Array<ProductSale>>,
  'getFarmer' : ActorMethod<[FarmerID], Farmer>,
  'getFarmerBalance' : ActorMethod<[FarmerID], number>,
  'getFarmerTransactions' : ActorMethod<[FarmerID, bigint], Array<Transaction>>,
  'getPaginatedCollections' : ActorMethod<
    [FarmerID, bigint],
    Array<CollectionEntry>
  >,
  'getRates' : ActorMethod<[], { 'vlc' : number, 'thekadari' : number }>,
  'updateCollectionEntry' : ActorMethod<
    [
      FarmerID,
      bigint,
      number,
      number,
      [] | [number],
      number,
      Session,
      MilkType,
    ],
    undefined
  >,
  'updateFarmerDetails' : ActorMethod<
    [FarmerID, string, string, MilkType, FarmerID],
    undefined
  >,
  'updateInventory' : ActorMethod<[string, number], undefined>,
  'updateProductSale' : ActorMethod<
    [bigint, [] | [FarmerID], string, number, number],
    undefined
  >,
  'updateRates' : ActorMethod<[number, number], undefined>,
  'updateTransaction' : ActorMethod<
    [FarmerID, bigint, string, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];