/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryEntry {
    quantityInStock: number;
    product: Product;
}
export type Time = bigint;
export interface ProductSale {
    id: bigint;
    farmerID?: FarmerID;
    productName: string;
    pricePerUnit: number;
    totalAmount: number;
    timestamp: Time;
    quantity: number;
}
export interface CollectionEntry {
    fat: number;
    snf?: number;
    weight: number;
    farmerID: FarmerID;
    date: Time;
    rate: number;
    milkType: MilkType;
    session: Session;
}
export type FarmerID = bigint;
export interface Farmer {
    name: string;
    milkType: MilkType;
    customerID: FarmerID;
    phone: string;
}
export interface Product {
    name: string;
}
export interface Transaction {
    id: bigint;
    farmerID: FarmerID;
    description: string;
    timestamp: Time;
    amount: number;
}
export enum MilkType {
    vlc = "vlc",
    thekadari = "thekadari"
}
export enum Session {
    morning = "morning",
    evening = "evening"
}
export interface backendInterface {
    addCollectionEntry(farmerID: FarmerID, weight: number, fat: number, snf: number | null, rate: number, session: Session): Promise<void>;
    addFarmer(name: string, phone: string, milkType: MilkType): Promise<FarmerID>;
    addInventoryEntry(productName: string, quantity: number): Promise<void>;
    addProductSale(farmerID: FarmerID | null, productName: string, quantity: number, pricePerUnit: number): Promise<bigint>;
    addTransaction(farmerID: FarmerID, description: string, amount: number): Promise<bigint>;
    getAllCollectionsForSession(session: Session, page: bigint): Promise<Array<CollectionEntry>>;
    getAllFarmers(): Promise<Array<Farmer>>;
    getAllInventory(): Promise<Array<InventoryEntry>>;
    getAllProductSales(): Promise<Array<ProductSale>>;
    getFarmer(id: FarmerID): Promise<Farmer>;
    getFarmerBalance(farmerID: FarmerID): Promise<number>;
    getFarmerTransactions(farmerID: FarmerID, page: bigint): Promise<Array<Transaction>>;
    getPaginatedCollections(farmerID: FarmerID, page: bigint): Promise<Array<CollectionEntry>>;
    getRates(): Promise<{
        vlc: number;
        thekadari: number;
    }>;
    updateFarmerDetails(id: FarmerID, name: string, phone: string, milkType: MilkType, customerID: FarmerID): Promise<void>;
    updateInventory(productName: string, quantity: number): Promise<void>;
    updateRates(vRate: number, tRate: number): Promise<void>;
}
import type { CollectionEntry as _CollectionEntry, Farmer as _Farmer, FarmerID as _FarmerID, MilkType as _MilkType, ProductSale as _ProductSale, Session as _Session, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCollectionEntry(arg0: FarmerID, arg1: number, arg2: number, arg3: number | null, arg4: number, arg5: Session): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollectionEntry(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Session_n2(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollectionEntry(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_Session_n2(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addFarmer(arg0: string, arg1: string, arg2: MilkType): Promise<FarmerID> {
        if (this.processError) {
            try {
                const result = await this.actor.addFarmer(arg0, arg1, to_candid_MilkType_n4(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFarmer(arg0, arg1, to_candid_MilkType_n4(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addInventoryEntry(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryEntry(arg0, arg1);
            return result;
        }
    }
    async addProductSale(arg0: FarmerID | null, arg1: string, arg2: number, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductSale(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductSale(to_candid_opt_n6(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async addTransaction(arg0: FarmerID, arg1: string, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllCollectionsForSession(arg0: Session, arg1: bigint): Promise<Array<CollectionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCollectionsForSession(to_candid_Session_n2(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCollectionsForSession(to_candid_Session_n2(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFarmers(): Promise<Array<Farmer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFarmers();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFarmers();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInventory(): Promise<Array<InventoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventory();
            return result;
        }
    }
    async getAllProductSales(): Promise<Array<ProductSale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductSales();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductSales();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmer(arg0: FarmerID): Promise<Farmer> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmer(arg0);
                return from_candid_Farmer_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmer(arg0);
            return from_candid_Farmer_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmerBalance(arg0: FarmerID): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerBalance(arg0);
            return result;
        }
    }
    async getFarmerTransactions(arg0: FarmerID, arg1: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerTransactions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerTransactions(arg0, arg1);
            return result;
        }
    }
    async getPaginatedCollections(arg0: FarmerID, arg1: bigint): Promise<Array<CollectionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedCollections(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedCollections(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRates(): Promise<{
        vlc: number;
        thekadari: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRates();
            return result;
        }
    }
    async updateFarmerDetails(arg0: FarmerID, arg1: string, arg2: string, arg3: MilkType, arg4: FarmerID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFarmerDetails(arg0, arg1, arg2, to_candid_MilkType_n4(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFarmerDetails(arg0, arg1, arg2, to_candid_MilkType_n4(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateInventory(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventory(arg0, arg1);
            return result;
        }
    }
    async updateRates(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRates(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CollectionEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionEntry): CollectionEntry {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Farmer_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Farmer): Farmer {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MilkType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MilkType): MilkType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ProductSale_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductSale): ProductSale {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FarmerID]): FarmerID | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    milkType: _MilkType;
    customerID: _FarmerID;
    phone: string;
}): {
    name: string;
    milkType: MilkType;
    customerID: FarmerID;
    phone: string;
} {
    return {
        name: value.name,
        milkType: from_candid_MilkType_n11(_uploadFile, _downloadFile, value.milkType),
        customerID: value.customerID,
        phone: value.phone
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    farmerID: [] | [_FarmerID];
    productName: string;
    pricePerUnit: number;
    totalAmount: number;
    timestamp: _Time;
    quantity: number;
}): {
    id: bigint;
    farmerID?: FarmerID;
    productName: string;
    pricePerUnit: number;
    totalAmount: number;
    timestamp: Time;
    quantity: number;
} {
    return {
        id: value.id,
        farmerID: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.farmerID)),
        productName: value.productName,
        pricePerUnit: value.pricePerUnit,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        quantity: value.quantity
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fat: number;
    snf: [] | [number];
    weight: number;
    farmerID: _FarmerID;
    date: _Time;
    rate: number;
    milkType: _MilkType;
    session: _Session;
}): {
    fat: number;
    snf?: number;
    weight: number;
    farmerID: FarmerID;
    date: Time;
    rate: number;
    milkType: MilkType;
    session: Session;
} {
    return {
        fat: value.fat,
        snf: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.snf)),
        weight: value.weight,
        farmerID: value.farmerID,
        date: value.date,
        rate: value.rate,
        milkType: from_candid_MilkType_n11(_uploadFile, _downloadFile, value.milkType),
        session: from_candid_Session_n13(_uploadFile, _downloadFile, value.session)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vlc: null;
} | {
    thekadari: null;
}): MilkType {
    return "vlc" in value ? MilkType.vlc : "thekadari" in value ? MilkType.thekadari : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
}): Session {
    return "morning" in value ? Session.morning : "evening" in value ? Session.evening : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Farmer>): Array<Farmer> {
    return value.map((x)=>from_candid_Farmer_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductSale>): Array<ProductSale> {
    return value.map((x)=>from_candid_ProductSale_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectionEntry>): Array<CollectionEntry> {
    return value.map((x)=>from_candid_CollectionEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_MilkType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MilkType): _MilkType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Session_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): _Session {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmerID | null): [] | [_FarmerID] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): {
    morning: null;
} | {
    evening: null;
} {
    return value == Session.morning ? {
        morning: null
    } : value == Session.evening ? {
        evening: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MilkType): {
    vlc: null;
} | {
    thekadari: null;
} {
    return value == MilkType.vlc ? {
        vlc: null
    } : value == MilkType.thekadari ? {
        thekadari: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
